"use client";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const APP_NAME = "Seevak Care";
const SUPPORT  = "seevakcare@gmail.com | +919771365160";

const s = StyleSheet.create({
  page:        { padding: 40, fontFamily: "Helvetica", backgroundColor: "#ffffff" },
  header:      { flexDirection: "row", justifyContent: "space-between", marginBottom: 20, borderBottomWidth: 2, borderBottomColor: "#0284c7", paddingBottom: 12 },
  appName:     { fontSize: 22, fontWeight: "bold", color: "#0284c7" },
  appSub:      { fontSize: 10, color: "#64748b" },
  docTitle:    { fontSize: 14, fontWeight: "bold", color: "#1e293b", marginBottom: 2 },
  docId:       { fontSize: 9, color: "#94a3b8" },
  infoGrid:    { flexDirection: "row", gap: 16, marginVertical: 16, backgroundColor: "#f0f9ff", padding: 12, borderRadius: 6 },
  infoBlock:   { flex: 1 },
  label:       { fontSize: 9, color: "#0284c7", textTransform: "uppercase", marginBottom: 3, fontWeight: "bold" },
  value:       { fontSize: 11, color: "#1e293b" },
  sectionHead: { fontSize: 11, fontWeight: "bold", color: "#0f172a", backgroundColor: "#e0f2fe", padding: "6 10", borderRadius: 4, marginTop: 14, marginBottom: 6 },
  row:         { flexDirection: "row", padding: "5 8", borderBottomWidth: 1, borderBottomColor: "#f1f5f9" },
  th:          { flex: 1, fontSize: 9, fontWeight: "bold", color: "#64748b", textTransform: "uppercase" },
  td:          { flex: 1, fontSize: 10, color: "#334155" },
  bullet:      { fontSize: 10, color: "#334155", marginBottom: 4, marginLeft: 8 },
  footer:      { position: "absolute", bottom: 28, left: 40, right: 40, textAlign: "center", fontSize: 8, color: "#94a3b8", borderTopWidth: 1, borderTopColor: "#e2e8f0", paddingTop: 8 },
  badge:       { fontSize: 9, fontWeight: "bold", color: "#0284c7", backgroundColor: "#e0f2fe", padding: "2 6", borderRadius: 4 },
});

export function PrescriptionPDF({ prescription }: { prescription: any }) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <View>
            <Text style={s.appName}>{APP_NAME}</Text>
            <Text style={s.appSub}>Healthcare Management Platform</Text>
          </View>
          <View style={{ alignItems: "flex-end" }}>
            <Text style={s.docTitle}>PRESCRIPTION</Text>
            <Text style={s.docId}>#{prescription.id?.slice(-10).toUpperCase()}</Text>
            <Text style={s.docId}>{new Date(prescription.createdAt).toDateString()}</Text>
          </View>
        </View>

        <View style={s.infoGrid}>
          <View style={s.infoBlock}>
            <Text style={s.label}>Patient</Text>
            <Text style={s.value}>{prescription.patient?.user?.name}</Text>
            <Text style={[s.value, { fontSize: 9, color: "#64748b" }]}>{prescription.patient?.user?.email}</Text>
          </View>
          <View style={s.infoBlock}>
            <Text style={s.label}>Doctor</Text>
            <Text style={s.value}>Dr. {prescription.doctor?.user?.name}</Text>
            <Text style={[s.value, { fontSize: 9, color: "#64748b" }]}>{prescription.doctor?.specialization}</Text>
            <Text style={[s.value, { fontSize: 9, color: "#64748b" }]}>{prescription.doctor?.qualifications}</Text>
          </View>
        </View>

        <Text style={s.sectionHead}>Diagnosis</Text>
        <Text style={[s.value, { marginLeft: 8 }]}>{prescription.diagnosis}</Text>

        {prescription.medicines?.length > 0 && (
          <>
            <Text style={s.sectionHead}>Prescribed Medicines</Text>
            <View style={[s.row, { backgroundColor: "#f8fafc" }]}>
              {["Medicine", "Dosage", "Frequency", "Duration"].map((h) => (
                <Text key={h} style={s.th}>{h}</Text>
              ))}
            </View>
            {prescription.medicines.map((m: any, i: number) => (
              <View key={i} style={s.row}>
                <Text style={s.td}>{m.medicineName}</Text>
                <Text style={s.td}>{m.dosage}</Text>
                <Text style={s.td}>{m.frequency}</Text>
                <Text style={s.td}>{m.duration}</Text>
              </View>
            ))}
          </>
        )}

        {prescription.labTests?.length > 0 && (
          <>
            <Text style={s.sectionHead}>Lab Tests Ordered</Text>
            {prescription.labTests.map((t: any, i: number) => (
              <Text key={i} style={s.bullet}>
                • {t.testName}{t.instructions ? ` — ${t.instructions}` : ""}
              </Text>
            ))}
          </>
        )}

        {prescription.notes && (
          <>
            <Text style={s.sectionHead}>Doctor Notes</Text>
            <Text style={[s.value, { marginLeft: 8 }]}>{prescription.notes}</Text>
          </>
        )}

        <Text style={s.footer}>
          Generated by {APP_NAME} · {SUPPORT} · This is a computer-generated prescription.
        </Text>
      </Page>
    </Document>
  );
}

export function LabReportPDF({ booking }: { booking: any }) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <View>
            <Text style={s.appName}>{APP_NAME}</Text>
            <Text style={s.appSub}>{booking.labStore?.name}</Text>
          </View>
          <View style={{ alignItems: "flex-end" }}>
            <Text style={s.docTitle}>LAB REPORT</Text>
            <Text style={s.docId}>#{booking.id?.slice(-10).toUpperCase()}</Text>
            <Text style={s.docId}>{new Date(booking.updatedAt).toDateString()}</Text>
          </View>
        </View>

        <View style={s.infoGrid}>
          <View style={s.infoBlock}>
            <Text style={s.label}>Patient</Text>
            <Text style={s.value}>{booking.patient?.user?.name}</Text>
          </View>
          <View style={s.infoBlock}>
            <Text style={s.label}>Test</Text>
            <Text style={s.value}>{booking.labTest?.name}</Text>
            <Text style={[s.value, { fontSize: 9, color: "#64748b" }]}>Sample: {booking.labTest?.sampleType}</Text>
          </View>
          <View style={s.infoBlock}>
            <Text style={s.label}>Status</Text>
            <Text style={s.badge}>REPORT READY</Text>
          </View>
        </View>

        <Text style={s.sectionHead}>Report Details</Text>
        <Text style={[s.value, { marginLeft: 8, color: "#64748b" }]}>
          Report URL: {booking.reportUrl}
        </Text>

        <Text style={s.footer}>
          Generated by {APP_NAME} · {SUPPORT} · This is a computer-generated document.
        </Text>
      </Page>
    </Document>
  );
}
